import os
import httpx
from fastapi import APIRouter, HTTPException, Request, Response, Depends
from fastapi.responses import RedirectResponse
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from datetime import datetime, timezone
from database import AsyncSessionLocal
from models import User, RefreshToken
from auth import (
    create_access_token, create_refresh_token,
    save_refresh_token, get_current_user
)
from schemas import RefreshRequest

router = APIRouter(prefix="/auth", tags=["auth"])

GITHUB_CLIENT_ID = os.getenv("GITHUB_CLIENT_ID")
GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET")
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")


@router.get("/github")
async def github_login(request: Request):
    # state is generated by the CLI or browser — passed through as query param
    state = request.query_params.get("state", "")
    code_challenge = request.query_params.get("code_challenge", "")

    params = (
        f"client_id={GITHUB_CLIENT_ID}"
        f"&scope=user:email"
        f"&state={state}"
    )
    return RedirectResponse(f"https://github.com/login/oauth/authorize?{params}")


@router.get("/github/callback")
async def github_callback(code: str, state: str, request: Request):
    # Exchange code for GitHub access token
    async with httpx.AsyncClient() as client:
        token_res = await client.post(
            "https://github.com/login/oauth/access_token",
            json={
                "client_id": GITHUB_CLIENT_ID,
                "client_secret": GITHUB_CLIENT_SECRET,
                "code": code,
            },
            headers={"Accept": "application/json"}
        )
        token_data = token_res.json()

    github_token = token_data.get("access_token")
    if not github_token:
        raise HTTPException(status_code=502, detail={
            "status": "error",
            "message": "Failed to obtain GitHub access token"
        })

    # Fetch GitHub user info
    async with httpx.AsyncClient() as client:
        user_res = await client.get(
            "https://api.github.com/user",
            headers={"Authorization": f"Bearer {github_token}"}
        )
        github_user = user_res.json()

    async with AsyncSessionLocal() as session:
        result = await session.execute(
            select(User).where(User.github_id == str(github_user["id"]))
        )
        user = result.scalar_one_or_none()

        if not user:
            user = User(
                github_id=str(github_user["id"]),
                username=github_user.get("login"),
                email=github_user.get("email"),
                avatar_url=github_user.get("avatar_url"),
                role="analyst"
            )
            session.add(user)

        user.last_login_at = datetime.now(timezone.utc)
        await session.commit()
        await session.refresh(user)

    access_token = create_access_token(str(user.id), user.role)
    refresh_token = create_refresh_token()
    await save_refresh_token(str(user.id), refresh_token)

    return {
        "status": "success",
        "access_token": access_token,
        "refresh_token": refresh_token,
        "user": {
            "id": str(user.id),
            "username": user.username,
            "email": user.email,
            "role": user.role,
            "avatar_url": user.avatar_url
        }
    }


@router.post("/refresh")
async def refresh_token(body: RefreshRequest):
    async with AsyncSessionLocal() as session:
        result = await session.execute(
            select(RefreshToken).where(RefreshToken.token == body.refresh_token)
        )
        stored = result.scalar_one_or_none()

        if not stored or stored.is_revoked:
            raise HTTPException(status_code=401, detail={
                "status": "error",
                "message": "Invalid refresh token"
            })

        if stored.expires_at < datetime.now(timezone.utc):
            raise HTTPException(status_code=401, detail={
                "status": "error",
                "message": "Refresh token expired"
            })

        # Invalidate old token immediately
        stored.is_revoked = True
        await session.commit()

        # Fetch user
        user_result = await session.execute(
            select(User).where(User.id == stored.user_id)
        )
        user = user_result.scalar_one_or_none()

    if not user or not user.is_active:
        raise HTTPException(status_code=403, detail={
            "status": "error",
            "message": "User not found or deactivated"
        })

    # Issue new pair
    new_access = create_access_token(str(user.id), user.role)
    new_refresh = create_refresh_token()
    await save_refresh_token(str(user.id), new_refresh)

    return {
        "status": "success",
        "access_token": new_access,
        "refresh_token": new_refresh
    }


@router.post("/logout")
async def logout(current_user: User = Depends(get_current_user), body: RefreshRequest = None):
    if body and body.refresh_token:
        async with AsyncSessionLocal() as session:
            result = await session.execute(
                select(RefreshToken).where(RefreshToken.token == body.refresh_token)
            )
            stored = result.scalar_one_or_none()
            if stored:
                stored.is_revoked = True
                await session.commit()

    return {"status": "success", "message": "Logged out successfully"}


@router.get("/me")
async def get_me(current_user: User = Depends(get_current_user)):
    return {
        "status": "success",
        "data": {
            "id": str(current_user.id),
            "username": current_user.username,
            "email": current_user.email,
            "role": current_user.role,
            "avatar_url": current_user.avatar_url,
            "last_login_at": current_user.last_login_at.isoformat() if current_user.last_login_at else None
        }
    }